# dubbo服务配置
dubbo:
  scan:
    base-packages: com.zss.app.service
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services: 'application-service'