spring:
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    suffix: .html
    encoding: utf-8
    servlet:
      content-type: text/html
    mode: HTML

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
