server:
  port: 9080

spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/esms
    username: esms_admin
    password: esms_admin
    driver-class-name: org.postgresql.Driver

