server:
  port: 8888

spring:

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/emp
    username: emp_test
    password: 123456
    driver-class-name: org.postgresql.Driver

config:
  jwt:
    # 加密密钥
    secret: asdfghjkl123
    # token 过期时间(ms)
    expire: 60000
    # header 名称
    header: token
    # issuer 签发者
    issuer: ZSS
    # subject 主题
    subject: demo
